package solutions;

/*
Question 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

public class EvenFibonacci {

    public static int EvenFibonacciSum() {

        int total = 0;
        int t1 = 1, t2 = 2;


        while (t1 < 4_000_000) {

            if (t2 % 2 == 0) {
                total += t2;
            }
            int temp = t2+t1;
            t1 = t2;
            t2 = temp;
        }

        return total;
    }

    public static void main(String[] args) {

        System.out.println(EvenFibonacciSum());
    }
}
